### ISSUE TITLE
libcmis does not build with icu 64.1

### ISSUE THREAD

**Issue by wblaszcz** [tdf/libcmis#35]
I get the following error:

Making all in libcmis-c
make[2]: Entering directory '/home/lfs/libcmis/src/libcmis-c'
  CXX      libcmis_c_0.5_la-repository.lo
In file included from /usr/include/c++/8.3.0/bits/stl_algobase.h:63,
                 from /usr/include/c++/8.3.0/memory:62,
                 from /usr/include/unicode/localpointer.h:45,
                 from /usr/include/unicode/uenum.h:23,
                 from /usr/include/unicode/ucnv.h:53,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:810,
                 from /usr/include/libxml2/libxml/globals.h:18,
                 from /usr/include/libxml2/libxml/threads.h:35,
                 from /usr/include/libxml2/libxml/xmlmemory.h:218,
                 from /usr/include/libxml2/libxml/tree.h:1307,
                 from ../../inc/libcmis-c/repository.h:35,
                 from repository.cxx:29:
/usr/include/c++/8.3.0/ext/numeric_traits.h:54:3: error: template with C linkage
   template<typename _Value>
   ^~~~~~~~
In file included from repository.cxx:29:
../../inc/libcmis-c/repository.h:32:1: note: ‘extern "C"’ linkage started here
 extern "C" {
 ^~~~~~~~~~
In file included from /usr/include/c++/8.3.0/bits/stl_algobase.h:63,
                 from /usr/include/c++/8.3.0/memory:62,
                 from /usr/include/unicode/localpointer.h:45,
                 from /usr/include/unicode/uenum.h:23,
                 from /usr/include/unicode/ucnv.h:53,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:810,
                 from /usr/include/libxml2/libxml/globals.h:18,
                 from /usr/include/libxml2/libxml/threads.h:35,
                 from /usr/include/libxml2/libxml/xmlmemory.h:218,
                 from /usr/include/libxml2/libxml/tree.h:1307,
                 from ../../inc/libcmis-c/repository.h:35,
                 from repository.cxx:29:
/usr/include/c++/8.3.0/ext/numeric_traits.h:67:3: error: template with C linkage
   template<typename _Value>
   ^~~~~~~~
n file included from repository.cxx:29:
../../inc/libcmis-c/repository.h:32:1: note: ‘extern "C"’ linkage started here
 extern "C" {
 ^~~~~~~~~~
In file included from /usr/include/c++/8.3.0/bits/stl_algobase.h:63,
                 from /usr/include/c++/8.3.0/memory:62,
                 from /usr/include/unicode/localpointer.h:45,
                 from /usr/include/unicode/uenum.h:23,
                 from /usr/include/unicode/ucnv.h:53,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:810,
                 from /usr/include/libxml2/libxml/globals.h:18,
                 from /usr/include/libxml2/libxml/threads.h:35,
                 from /usr/include/libxml2/libxml/xmlmemory.h:218,
                 from /usr/include/libxml2/libxml/tree.h:1307,
                 from ../../inc/libcmis-c/repository.h:35,
                 from repository.cxx:29:
/usr/include/c++/8.3.0/ext/numeric_traits.h:70:3: error: template with C linkage
   template<typename _Value>
   ^~~~~~~~
In file included from repository.cxx:29:
../../inc/libcmis-c/repository.h:32:1: note: ‘extern "C"’ linkage started here
 extern "C" {
 ^~~~~~~~~~
In file included from /usr/include/c++/8.3.0/bits/stl_algobase.h:63,
                 from /usr/include/c++/8.3.0/memory:62,
                 from /usr/include/unicode/localpointer.h:45,
                 from /usr/include/unicode/uenum.h:23,
                 from /usr/include/unicode/ucnv.h:53,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:810,
                 from /usr/include/libxml2/libxml/globals.h:18,
                 from /usr/include/libxml2/libxml/threads.h:35,
                 from /usr/include/libxml2/libxml/xmlmemory.h:218,
                 from /usr/include/libxml2/libxml/tree.h:1307,
                 from ../../inc/libcmis-c/repository.h:35,
                 from repository.cxx:29:
/usr/include/c++/8.3.0/ext/numeric_traits.h:73:3: error: template with C linkage
   template<typename _Value>
   ^~~~~~~~

.... etc

In file included from repository.cxx:29:
../../inc/libcmis-c/repository.h:32:1: note: ‘extern "C"’ linkage started here
 extern "C" {
 ^~~~~~~~~~
In file included from /usr/include/unicode/localpointer.h:45,
                 from /usr/include/unicode/uenum.h:23,
                 from /usr/include/unicode/ucnv.h:53,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:810,
                 from /usr/include/libxml2/libxml/globals.h:18,
                 from /usr/include/libxml2/libxml/threads.h:35,
                 from /usr/include/libxml2/libxml/xmlmemory.h:218,
                 from /usr/include/libxml2/libxml/tree.h:1307,
                 from ../../inc/libcmis-c/repository.h:35,
                 from repository.cxx:29:
/usr/include/c++/8.3.0/memory:135:1: error: template with C linkage
 template <typename _Tp>
 ^~~~~~~~
In file included from repository.cxx:29:
../../inc/libcmis-c/repository.h:32:1: note: ‘extern "C"’ linkage started here
 extern "C" {
 ^~~~~~~~~~
make[2]: *** [Makefile:614: libcmis_c_0.5_la-repository.lo] Error 1
make[2]: Leaving directory '/home/lfs/libcmis/src/libcmis-c'
make[1]: *** [Makefile:522: all-recursive] Error 1
make[1]: Leaving directory '/home/lfs/libcmis/src'
make: *** [Makefile:536: all-recursive] Error 1

**Comment by dtardon** [comment]
A known problem: https://github.com/unicode-org/icu/pull/572 .

**Comment by Arfrever** [comment]
ICU upstream, after discussion in https://unicode-org.atlassian.net/browse/ICU-20530, decided that headers should not be included inside `extern "C" {` block.

Necessary patch for libcmis created by `Andreas Sturmlechner <asturm@gentoo.org>`:
```
--- a/inc/libcmis-c/repository.h	2018-12-27 14:07:55.000000000 +0100
+++ b/inc/libcmis-c/repository.h	2019-04-21 01:29:46.504373226 +0200
@@ -28,12 +28,12 @@
 #ifndef _REPOSITORY_H_
 #define _REPOSITORY_H_
 
+#include <libxml/tree.h>
+
 #ifdef __cplusplus
 extern "C" {
 #endif
 
-#include <libxml/tree.h>
-
 #include "libcmis-c/libcmis-c-api.h"
 #include "libcmis-c/types.h"
 
```

**Comment by iainlane** [comment]
Can this be reopened & the diff up there committed ideally please? It's happening in Ubuntu atm and will in Debian soon.
